### ISSUE TITLE
Question: Limitations

### ISSUE THREAD

**Issue by vishal3007** [jeronimonunes/PEG#1]
Hi, 
By looking at the code it seems to me is that the utility can support all the functionality of the corresponding peg.js file. 
Do you see any limitation of the Java adapter in comparison of the peg.js uses?

Thanks,
Vishal

**Comment by jeronimonunes** [comment]
The only limitation is according to the JavaScript you use because of the underlying JavaScript implementation (Nashorn or Rhino). The functionality of pegjs itself I belive are all preserved.

**Comment by vishal3007** [comment]
This is my understanding as well...Thanks for the quick response
